#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | foamTEX: Open Source CFD to laTeX
#  \\    /   O peration     | Web: https://github.com/LeoTurnell-Ritson/foamTEX
#   \\  /    A nd           | For copyright notice see file Copyright
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
#
# Description
#  Basic make script using pyinstaller
#  (see https://pypi.org/project/pyinstaller/)
#
#------------------------------------------------------------------------------

pyinstaller -F src/foamTEX.py

# ----------------------------------------------------------------- end-of-file
